### ISSUE TITLE
Expreso does not support negative numbers

### ISSUE THREAD

**Issue by arnomi** [ympons/expreso#2]
Expreso currently does not support negative numbers. This should, however, be easily fixable by lexing ints and floats as

```
INT   = (\-*[0-9]+)
FLOAT = (\-*[0-9]+\.[0-9]*)
```

**Comment by ympons** [comment]
@arnomi Thanks for checking the lib, but I am not sure if your statement is totally correct.
The current version supports negative numbers. You can check the lexer [here](https://github.com/ympons/expreso/blob/master/src/expreso_lexer.xrl#L4).

**Comment by ympons** [comment]
@arnomi Closing this! Feel free to reopen this issue if you have any related questions.

**Comment by arnomi** [comment]
@ympons I was somehow stuck on an older version. Thanks for the quick response and the nice work.
